version: '3.7'

services:
  mysql8:
    env_file:
      - .env
    image: mysql:8
    container_name: ${NAME:-mysql8_local}
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
      - SYS_PTRACE
      - SYS_RESOURCE
    command: [
        --innodb-dedicated-server=ON,
        --default-authentication-plugin=mysql_native_password
        ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql8_data:/var/lib/mysql
      - ./custom:/etc/mysql/conf.d
      - ./provision:/root/provision:rw
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '3'
    deploy:
      resources:
        limits:
          #cpus: '0.92'
          memory: 1786M
        reservations:
          #cpus: '0.5'
          memory: 768M

volumes:
  mysql8_data:

networks:
  default:
    external:
      name: ${NETWORK:-default}
